---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: exo3
spec:
  type: NodePort 
  selector: 
    app : flaskapp
  ports:
  - port: 80
    targetPort: 5000     
    nodePort: 32000
    protocol: TCP 