---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  namespace: exo3
  labels:
    app: mariadb

spec:
  containers:
  - name: mariadb-container
    image: mariadb:10.4
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mariadb-volume
    resources: 
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: juve
  volumes: 
  - name: mariadb-volume
    persistentVolumeClaim:
      claimName: mariadb-pvc
