---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc 
  namespace: exo3
spec:
  type: ClusterIP 
  selector: 
    app : mariadb
  ports:
  - port: 3306
    targetPort: 3306     
    protocol: TCP 